---
- name: clone weight tracker git repo
  git:
    repo: https://github.com/vikrantx/bootcamp-app.git
    dest: ~/weight-tracker-app
    clone: yes
    update: yes
    force: yes

- name: copy .env file into application folder
  tags: copy
  template: 
    src: .env.j2
    dest: ~/weight-tracker-app/.env
    owner: azureuser
    group: azureuser
    mode: 0755

- name: Install node packages
  shell: cd ~/weight-tracker-app && sudo npm install
  args:
    executable: /bin/bash

- name: Create weight tracker db 
  tags: db_setup
  run_once: true
  shell: psql  "host={{ db_host }} port=5432 dbname=postgres user={{ db_username }} password={{ db_password }}" -tc "SELECT 1 FROM pg_database WHERE datname = 'weight-tracker-db'" | grep -q 1 || psql "host={{ db_host }} port=5432 dbname=postgres user={{ db_username }} password={{ db_password }}" -c '\x' -c 'CREATE DATABASE "weight-tracker-db";'
  args:
    executable: /bin/bash

- name: Create tables 
  tags: db_setup
  run_once: true
  shell: cd ~/weight-tracker-app && npm run initdb
  args:
    executable: /bin/bash    

- name: Install pm2 
  tags: install_pm2
  become: true
  become_method: sudo
  shell: npm install pm2@latest -g
  args:
    executable: /bin/bash

- name: start application with pm2 
  tags: start_application
  shell: cd ~/weight-tracker-app && pm2 delete "weight-tracker"; pm2 startup && pm2 start src/index.js --name "weight-tracker" && pm2 save
  args:
    executable: /bin/bash

