---

- name: copy .env file into application folder
  tags: copy
  template: 
    src: .env.j2
    dest: ~/mount/data/.env
    owner: azureuser
    group: azureuser
    mode: 0755

- name: Create weight tracker db 
  tags: db_setup
  run_once: true
  shell: psql  "host={{ db_host }} port=5432 dbname=postgres user={{ db_username }} password={{ db_password }}" -tc "SELECT 1 FROM pg_database WHERE datname = 'weight-tracker-db'" | grep -q 1 || psql "host={{ db_host }} port=5432 dbname=postgres user={{ db_username }} password={{ db_password }}" -c '\x' -c 'CREATE DATABASE "weight-tracker-db";'
  args:
    executable: /bin/bash
